"""Creating all tables

Revision ID: 3a528d9cc12f
Revises: 
Create Date: 2021-09-12 09:51:35.074959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a528d9cc12f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.Unicode(length=250), nullable=True),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('birthday',
    sa.Column('birthday_id', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('birthday_id')
    )
    op.create_table('email',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('phone',
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('phone_id')
    )
    op.create_table('username',
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Unicode(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name_id')
    )
    op.create_table('record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('birthday_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['birthday_id'], ['birthday.birthday_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['email.email_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['name_id'], ['username.name_id'], ),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('name_id')
    )
    op.create_table('phone_record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('phone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['phone.phone_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['record_id'], ['record.record_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', 'phone_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_record')
    op.drop_table('record')
    op.drop_table('username')
    op.drop_table('phone')
    op.drop_table('email')
    op.drop_table('birthday')
    op.drop_table('address')
    # ### end Alembic commands ###
